/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_de_control_y_acceso;

import conexion.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin Martinez
 */
public class frm_control_clientes extends javax.swing.JFrame {
    
    DefaultTableModel cliente;

    /**
     * Creates new form frm_control_clientes
     */
    
    public frm_control_clientes() {
        initComponents();
        this.cliente = (DefaultTableModel) tbl_clientes.getModel();
        Mostrardatos("");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
    public void Limpiar(){
        
        //Limpia los campos en control de clientes
        txt_nombrecliente.setText("");
        txt_apellidoscliente.setText("");
        txt_cedulacliente.setText("");
        txt_sexocliente.setText("");
    
    }
    
    public void RefrescarTabla(){
        
        //Funcion encargada de refrescar la tabla utilizando Revalidate
        try {
        cliente.setColumnCount(0);
        cliente.setRowCount(0);
        tbl_clientes.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
   
          }
    
     public final void Mostrardatos(String valor){
         
        //Funcion para llenar la tabla de Usuarios desde la base de datos
        MyConnection cc=new MyConnection();
        Connection cn=MyConnection.getConnection();
        RefrescarTabla();
        cliente.addColumn("ID");
        cliente.addColumn("Nombre");
        cliente.addColumn("Apellidos");
        cliente.addColumn("Cédula");
        cliente.addColumn("Sexo");
            
        this.tbl_clientes.setModel(cliente);
        String sql;
            
        if (valor.equals(""))
            {
            sql="SELECT * FROM cliente";
            }
           
        else{
            sql="SELECT * FROM cliente WHERE ID_cliente='"+valor+"'";
            } 
            //Declaración de arreglo para llenar la tabla de clientes
            String []datos=new String [5];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                
            //Orden de posiciones
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);

            cliente.addRow(datos);
            }
            tbl_clientes.setModel(cliente);
            
            //Mensaje de error
            }catch(SQLException ex){
            Logger.getLogger(frm_control_clientes.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedor = new javax.swing.JPanel();
        jp_encabezado = new javax.swing.JPanel();
        lbl_controlusuario = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jp_contenedordatos = new javax.swing.JPanel();
        lbl_nombrecliente = new javax.swing.JLabel();
        txt_nombrecliente = new javax.swing.JTextField();
        lbl_sexocliente = new javax.swing.JLabel();
        txt_apellidoscliente = new javax.swing.JTextField();
        lbl_cedulacliente = new javax.swing.JLabel();
        btn_agregarcliente = new javax.swing.JButton();
        btn_editarcliente = new javax.swing.JButton();
        btn_eliminarcliente = new javax.swing.JButton();
        txt_cedulacliente = new javax.swing.JTextField();
        lbl_apellidoscliente = new javax.swing.JLabel();
        txt_sexocliente = new javax.swing.JTextField();
        jsc_tablaclientes = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        jp_marcoinferior = new javax.swing.JPanel();
        jp_marcosuperior = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_contenedor.setBackground(new java.awt.Color(255, 255, 255));

        jp_encabezado.setBackground(new java.awt.Color(255, 255, 255));

        lbl_controlusuario.setFont(new java.awt.Font("Britannic Bold", 1, 28)); // NOI18N
        lbl_controlusuario.setText("CONTROL DE CLIENTES");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jp_encabezadoLayout = new javax.swing.GroupLayout(jp_encabezado);
        jp_encabezado.setLayout(jp_encabezadoLayout);
        jp_encabezadoLayout.setHorizontalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_controlusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_encabezadoLayout.setVerticalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_logo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_controlusuario)
                .addGap(34, 34, 34))
        );

        jp_contenedordatos.setBackground(new java.awt.Color(234, 234, 234));

        lbl_nombrecliente.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombrecliente.setText("Nombre");

        txt_nombrecliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreclienteActionPerformed(evt);
            }
        });

        lbl_sexocliente.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_sexocliente.setText("Sexo");

        txt_apellidoscliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_cedulacliente.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_cedulacliente.setText("Cédula");
        lbl_cedulacliente.setToolTipText("");

        btn_agregarcliente.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        btn_agregarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearusuario_ico.png"))); // NOI18N
        btn_agregarcliente.setToolTipText("Registrar Cliente");
        btn_agregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarclienteActionPerformed(evt);
            }
        });

        btn_editarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificarusuario_ico.png"))); // NOI18N
        btn_editarcliente.setToolTipText("Editar Cliente");
        btn_editarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarclienteActionPerformed(evt);
            }
        });

        btn_eliminarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarusuario_ico.png"))); // NOI18N
        btn_eliminarcliente.setToolTipText("Eliminar CLiente");
        btn_eliminarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarclienteActionPerformed(evt);
            }
        });

        txt_cedulacliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_apellidoscliente.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_apellidoscliente.setText("Apellidos");

        txt_sexocliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jp_contenedordatosLayout = new javax.swing.GroupLayout(jp_contenedordatos);
        jp_contenedordatos.setLayout(jp_contenedordatosLayout);
        jp_contenedordatosLayout.setHorizontalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                                .addComponent(btn_agregarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(btn_eliminarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_nombrecliente)
                            .addComponent(txt_apellidoscliente)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosLayout.createSequentialGroup()
                                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cedulacliente)
                                    .addComponent(txt_cedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_sexocliente)
                                    .addComponent(lbl_sexocliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombrecliente)
                            .addComponent(lbl_apellidoscliente))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp_contenedordatosLayout.setVerticalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombrecliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_apellidoscliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_apellidoscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedulacliente)
                    .addComponent(lbl_sexocliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_editarcliente)
                    .addComponent(btn_agregarcliente)
                    .addComponent(btn_eliminarcliente))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tbl_clientes.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientesSeleccionar(evt);
            }
        });
        jsc_tablaclientes.setViewportView(tbl_clientes);

        jp_marcoinferior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcoinferiorLayout = new javax.swing.GroupLayout(jp_marcoinferior);
        jp_marcoinferior.setLayout(jp_marcoinferiorLayout);
        jp_marcoinferiorLayout.setHorizontalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcoinferiorLayout.setVerticalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jp_marcosuperior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcosuperiorLayout = new javax.swing.GroupLayout(jp_marcosuperior);
        jp_marcosuperior.setLayout(jp_marcosuperiorLayout);
        jp_marcosuperiorLayout.setHorizontalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcosuperiorLayout.setVerticalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar_ico.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedorLayout = new javax.swing.GroupLayout(jp_contenedor);
        jp_contenedor.setLayout(jp_contenedorLayout);
        jp_contenedorLayout.setHorizontalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_marcoinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_marcosuperior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar))
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jsc_tablaclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30))
        );
        jp_contenedorLayout.setVerticalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addComponent(jp_marcosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addGap(28, 28, 28)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jsc_tablaclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jp_contenedordatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jp_marcoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreclienteActionPerformed

    private void btn_agregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarclienteActionPerformed
        
        //Declaración de variables
        String nom,ape,ced,sex;
        
        //Asignación de campos de los cuales toman los valores
        nom = txt_nombrecliente.getText();
        ape = txt_apellidoscliente.getText();
        ced = txt_cedulacliente.getText();
        sex = txt_sexocliente.getText();
        
        //Condicional IF para comprobar que no hayan campos vacíos
        if ( nom.isEmpty() || ape.isEmpty() || ced.isEmpty() || sex.isEmpty()){

            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos","error", 2);

        }else{
            
            //Declaración de consulta
            PreparedStatement ps;
            String query;
            
            //Creación de sentencia SQL para insertar los datos
            query = "INSERT INTO `cliente`(`nom_cliente`, `apellidos_cliente`, `cedula_cliente`,`sexo_cliente`) VALUES (?,?,?,?)";
            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, nom);
                ps.setString(2, ape);
                ps.setString(3, ced);
                ps.setString(4, sex);
                
                //Condicional IF para validar la inserción de datos
                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Agregado exitosamente!");
                    Mostrardatos("");
                    Limpiar();
                }

            } catch (SQLException ex) {
                Logger.getLogger(frm_control_clientes.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    }//GEN-LAST:event_btn_agregarclienteActionPerformed

    private void btn_editarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarclienteActionPerformed
        // TODO add your handling code here:
        
        //Toma los datos de los campos en control de clientes
        String id = (String)cliente.getValueAt(tbl_clientes.getSelectedRow(),0);
        String nom = txt_nombrecliente.getText();
        String ape = txt_apellidoscliente.getText();
        String ced = txt_cedulacliente.getText();
        String sex = txt_sexocliente.getText();
        
        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia SQL para actualizar los registros en la base de datos
        String query = "UPDATE cliente SET nom_cliente=?, apellidos_cliente=?, cedula_cliente=?, sexo_cliente=? WHERE ID_cliente=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(5, id);
            ps.setString(1, nom);
            ps.setString(2, ape);
            ps.setString(3, ced);
            ps.setString(4, sex);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cliente Modificado");
            Limpiar();
            Mostrardatos("");
        
         //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_editarclienteActionPerformed

    private void btn_eliminarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarclienteActionPerformed
        // TODO add your handling code here:
        
        //Declaracion de variable id con la posición 0
        String id = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),0);

        //Declaración de consulta 
        PreparedStatement ps;
        
        //Creación de sentencia SQL para eliminar un registro dado un ID
        String query = "DELETE FROM cliente WHERE ID_cliente=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, id);
            
            //Condicional IF para confirmar la eliminación de un registro
            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "Cliente Eliminado");
                Limpiar();
                Mostrardatos("");
            }
            
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_eliminarclienteActionPerformed

    private void tbl_clientesSeleccionar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesSeleccionar

        try {
            
            //Declaración de variables y las posiciones de sus campos en la tabla de clientes
            String id = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),0);
            String nom = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),1);
            String ape = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),2);
            String ced = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),3);
            String sex = (String) cliente.getValueAt(tbl_clientes.getSelectedRow(),4);

            txt_nombrecliente.setText(nom);
            txt_apellidoscliente.setText(ape);
            txt_cedulacliente.setText(ced);
            txt_sexocliente.setText(sex);

        }
        
        //Mensaje de error
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_tbl_clientesSeleccionar

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        //Método constructor para el main
        frm_main form = new frm_main();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_control_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_control_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_control_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_control_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el control de clientes
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_control_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarcliente;
    private javax.swing.JButton btn_editarcliente;
    private javax.swing.JButton btn_eliminarcliente;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel jp_contenedor;
    private javax.swing.JPanel jp_contenedordatos;
    private javax.swing.JPanel jp_encabezado;
    private javax.swing.JPanel jp_marcoinferior;
    private javax.swing.JPanel jp_marcosuperior;
    private javax.swing.JScrollPane jsc_tablaclientes;
    private javax.swing.JLabel lbl_apellidoscliente;
    private javax.swing.JLabel lbl_cedulacliente;
    private javax.swing.JLabel lbl_controlusuario;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombrecliente;
    private javax.swing.JLabel lbl_sexocliente;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTextField txt_apellidoscliente;
    private javax.swing.JTextField txt_cedulacliente;
    private javax.swing.JTextField txt_nombrecliente;
    private javax.swing.JTextField txt_sexocliente;
    // End of variables declaration//GEN-END:variables
}
