/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_de_control_y_acceso;
import conexion.MyConnection;
import facturacion.frm_facturacion_medicamentos;
import static facturacion.frm_facturacion_medicamentos.txt_nombreempleadomedic;
import static formularios_de_control_y_acceso.frm_main.nom_emp;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Edwin Martinez
 */
public class frm_login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public frm_login() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_desa = new javax.swing.JPanel();
        jp_contenedor = new javax.swing.JPanel();
        jp_contenedordatos = new javax.swing.JPanel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        btn_acceder = new javax.swing.JButton();
        jp_contenedorlogo = new javax.swing.JPanel();
        lbl_logo = new javax.swing.JLabel();
        lbl_iniciarsesion = new javax.swing.JLabel();
        jp_marcoinferior = new javax.swing.JPanel();
        jp_marcosuperior = new javax.swing.JPanel();

        javax.swing.GroupLayout lbl_desaLayout = new javax.swing.GroupLayout(lbl_desa);
        lbl_desa.setLayout(lbl_desaLayout);
        lbl_desaLayout.setHorizontalGroup(
            lbl_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        lbl_desaLayout.setVerticalGroup(
            lbl_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        jp_contenedor.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedordatos.setBackground(new java.awt.Color(237, 237, 237));

        lbl_usuario.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_usuario.setText("Usuario");

        txt_usuario.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_contraseña.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_contraseña.setText("Contraseña");

        txt_clave.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btn_acceder.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        btn_acceder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acceder_ico.png"))); // NOI18N
        btn_acceder.setText("Acceder");
        btn_acceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accederActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedordatosLayout = new javax.swing.GroupLayout(jp_contenedordatos);
        jp_contenedordatos.setLayout(jp_contenedordatosLayout);
        jp_contenedordatosLayout.setHorizontalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btn_acceder))
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_usuario)
                            .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl_contraseña)
                                .addComponent(txt_clave, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                .addComponent(txt_usuario)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jp_contenedordatosLayout.setVerticalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btn_acceder)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jp_contenedorlogo.setBackground(new java.awt.Color(255, 255, 255));

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        lbl_iniciarsesion.setFont(new java.awt.Font("Britannic Bold", 0, 28)); // NOI18N
        lbl_iniciarsesion.setText("INICIAR SESIÓN");

        javax.swing.GroupLayout jp_contenedorlogoLayout = new javax.swing.GroupLayout(jp_contenedorlogo);
        jp_contenedorlogo.setLayout(jp_contenedorlogoLayout);
        jp_contenedorlogoLayout.setHorizontalGroup(
            jp_contenedorlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorlogoLayout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_iniciarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jp_contenedorlogoLayout.setVerticalGroup(
            jp_contenedorlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorlogoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_logo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorlogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_iniciarsesion)
                .addGap(33, 33, 33))
        );

        jp_marcoinferior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcoinferiorLayout = new javax.swing.GroupLayout(jp_marcoinferior);
        jp_marcoinferior.setLayout(jp_marcoinferiorLayout);
        jp_marcoinferiorLayout.setHorizontalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcoinferiorLayout.setVerticalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jp_marcosuperior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcosuperiorLayout = new javax.swing.GroupLayout(jp_marcosuperior);
        jp_marcosuperior.setLayout(jp_marcosuperiorLayout);
        jp_marcosuperiorLayout.setHorizontalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcosuperiorLayout.setVerticalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_contenedorLayout = new javax.swing.GroupLayout(jp_contenedor);
        jp_contenedor.setLayout(jp_contenedorLayout);
        jp_contenedorLayout.setHorizontalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_marcosuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_marcoinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedorLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_contenedorlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jp_contenedorLayout.setVerticalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addComponent(jp_marcosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jp_contenedorlogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jp_marcoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_accederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accederActionPerformed
     
           // TODO add your handling code here:
           
        //Declaración de consulta 
        PreparedStatement ps;
        ResultSet rs;
        
        //Declaración de variables 
        String user,clave;
        
        //Asignación de valores
        user = txt_usuario.getText();
        clave = String.valueOf(txt_clave.getPassword());
        
        //Consulta que selecciona todos los datos de un usuario dado el usuario y la clave ingresada
        String query = "SELECT * FROM `usuario` WHERE `nombre_usuario`=? AND `clave`=?";
        
        //Condicional IF para enviar mensaje si hay algún campo vacío
        if(user.equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese Su Usuario");
            
        }
        
        else if(clave.equals("")){
            
            JOptionPane.showMessageDialog(null, "Ingrese Su Contraseña");
            
        } 
        
        else 
        
        //Uso de consulta previamente declarada
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
         
            ps.setString(1, user);
            ps.setString(2, clave);
            
            rs = ps.executeQuery();
            
            //Condicional IF para tomar valores
            if(rs.next())
            {
                String nom = rs.getString("nombre_usuario");
                String cla = rs.getString("clave");
                String rol = rs.getString("cod_rol");
                
                //Condicional IF para realizar el uso de roles, siendo 1 administrador y 2 usuario vendedor
                if(rol.equals("1")){
                    
                    frm_main form = new frm_main();
                    form.setVisible(true);
                    frm_main.nom_emp = rs.getString("nombre_empleado");
                    this.dispose();
                }
                
                else if (rol.equals("2")){
                    
                    frm_facturacion_medicamentos form = new frm_facturacion_medicamentos();
                    
                    form.setVisible(true);
                    String nom_emp = rs.getString("nombre_empleado");
                    txt_nombreempleadomedic.setText(nom_emp);
                    this.dispose();
                
                }

            }
            
            else{
                    JOptionPane.showMessageDialog(null, "Usuario o Clave Incorrectos", "Fallo en Acceso", 2);
            }
            
            //Mensaje de error
            }catch(SQLException ex){
                
            Logger.getLogger(frm_login.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            
            }   
                
    }//GEN-LAST:event_btn_accederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el login
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_acceder;
    private javax.swing.JPanel jp_contenedor;
    private javax.swing.JPanel jp_contenedordatos;
    private javax.swing.JPanel jp_contenedorlogo;
    private javax.swing.JPanel jp_marcoinferior;
    private javax.swing.JPanel jp_marcosuperior;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JPanel lbl_desa;
    private javax.swing.JLabel lbl_iniciarsesion;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
