/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_de_control_y_acceso;

import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import conexion.MyConnection;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin Martinez
 */
public class frm_control_usuarios extends javax.swing.JFrame {
    
    DefaultTableModel usuario;

    /**
     * Creates new form frm_register
     */
    public frm_control_usuarios() {
        
        initComponents();
        this.usuario = (DefaultTableModel) tbl_usuarios.getModel();
        Mostrardatos("");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
    public void Limpiar() {
        //Limpia los campos en el control de usuarios
        txt_nombre.setText("");
        txt_user.setText("");
        txt_clave.setText("");
       
    }
    public void RefrescarTabla(){
        //Funcion encargada de refrescar la tabla utilizando revalidate
        try {
            usuario.setColumnCount(0);
            usuario.setRowCount(0);
            tbl_usuarios.revalidate();
        }
        //Mensaje de error
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }
    
    public final void Mostrardatos (String valor){
        //Funcion para llenar la tabla de usuarios desde la BDD
        MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            usuario.addColumn("ID");
            usuario.addColumn("User");
            usuario.addColumn("Password");
            usuario.addColumn("Nombre");
            usuario.addColumn("Rol");
            
            this.tbl_usuarios.setModel(usuario);
            String sql;
            
            //Condicional IF para seleccionar un registro
            if (valor.equals(""))
            {
            sql="SELECT * FROM usuario";
            }
           
            else{
            sql="SELECT * FROM usuario WHERE ID_usuario='"+valor+"'";
            } 
            
            //Arreglo para llenar la tabla de usuarios
            String []datos=new String [5];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
  
           usuario.addRow(datos);
            }
            tbl_usuarios.setModel(usuario);
            }
            
            //Mensaje de error
            catch(SQLException ex){
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            
            
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_desa = new javax.swing.JPanel();
        jp_des = new javax.swing.JPanel();
        lbl_desa = new javax.swing.JLabel();
        jp_contenedor = new javax.swing.JPanel();
        jp_encabezado = new javax.swing.JPanel();
        lbl_controlusuario = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jp_contenedordatos = new javax.swing.JPanel();
        lbl_nombreusuario = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        lbl_user = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        txt_clave = new javax.swing.JPasswordField();
        btn_agregaruser = new javax.swing.JButton();
        btn_editaruser = new javax.swing.JButton();
        btn_eliminaruser = new javax.swing.JButton();
        lbl_rolusuario = new javax.swing.JLabel();
        txt_rol = new javax.swing.JComboBox<>();
        jsc_tblusuarios = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        jp_marcosuperior = new javax.swing.JPanel();
        jp_marcoinferior = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();

        javax.swing.GroupLayout jp_desaLayout = new javax.swing.GroupLayout(jp_desa);
        jp_desa.setLayout(jp_desaLayout);
        jp_desaLayout.setHorizontalGroup(
            jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jp_desaLayout.setVerticalGroup(
            jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jp_desLayout = new javax.swing.GroupLayout(jp_des);
        jp_des.setLayout(jp_desLayout);
        jp_desLayout.setHorizontalGroup(
            jp_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jp_desLayout.setVerticalGroup(
            jp_desLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lbl_desa.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jp_contenedor.setBackground(new java.awt.Color(255, 255, 255));

        jp_encabezado.setBackground(new java.awt.Color(255, 255, 255));

        lbl_controlusuario.setFont(new java.awt.Font("Britannic Bold", 1, 28)); // NOI18N
        lbl_controlusuario.setText("CONTROL DE USUARIOS");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jp_encabezadoLayout = new javax.swing.GroupLayout(jp_encabezado);
        jp_encabezado.setLayout(jp_encabezadoLayout);
        jp_encabezadoLayout.setHorizontalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_controlusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_encabezadoLayout.setVerticalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_logo))
            .addGroup(jp_encabezadoLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lbl_controlusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_contenedordatos.setBackground(new java.awt.Color(234, 234, 234));

        lbl_nombreusuario.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombreusuario.setText("Nombre");

        txt_nombre.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });

        lbl_user.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_user.setText("User");

        txt_user.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_password.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_password.setText("Password");
        lbl_password.setToolTipText("");

        txt_clave.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btn_agregaruser.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        btn_agregaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearusuario_ico.png"))); // NOI18N
        btn_agregaruser.setToolTipText("Registrar");
        btn_agregaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaruserActionPerformed(evt);
            }
        });

        btn_editaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificarusuario_ico.png"))); // NOI18N
        btn_editaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editaruserActionPerformed(evt);
            }
        });

        btn_eliminaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarusuario_ico.png"))); // NOI18N
        btn_eliminaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminaruserActionPerformed(evt);
            }
        });

        lbl_rolusuario.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_rolusuario.setText("Rol");

        txt_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "1", "2" }));
        txt_rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedordatosLayout = new javax.swing.GroupLayout(jp_contenedordatos);
        jp_contenedordatos.setLayout(jp_contenedordatosLayout);
        jp_contenedordatosLayout.setHorizontalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addComponent(lbl_nombreusuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                                .addComponent(btn_agregaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_password)
                                    .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_user))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbl_rolusuario)
                                            .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nombre)
                            .addComponent(txt_clave))
                        .addContainerGap())))
        );
        jp_contenedordatosLayout.setVerticalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombreusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_user)
                    .addComponent(lbl_rolusuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_rol, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(lbl_password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_editaruser)
                    .addComponent(btn_agregaruser)
                    .addComponent(btn_eliminaruser))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tbl_usuarios.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_usuariosSeleccionar(evt);
            }
        });
        jsc_tblusuarios.setViewportView(tbl_usuarios);

        jp_marcosuperior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcosuperiorLayout = new javax.swing.GroupLayout(jp_marcosuperior);
        jp_marcosuperior.setLayout(jp_marcosuperiorLayout);
        jp_marcosuperiorLayout.setHorizontalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcosuperiorLayout.setVerticalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jp_marcoinferior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcoinferiorLayout = new javax.swing.GroupLayout(jp_marcoinferior);
        jp_marcoinferior.setLayout(jp_marcoinferiorLayout);
        jp_marcoinferiorLayout.setHorizontalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcoinferiorLayout.setVerticalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar_ico.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedorLayout = new javax.swing.GroupLayout(jp_contenedor);
        jp_contenedor.setLayout(jp_contenedorLayout);
        jp_contenedorLayout.setHorizontalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar))
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jsc_tblusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
            .addComponent(jp_marcosuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_marcoinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jp_contenedorLayout.setVerticalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addComponent(jp_marcosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addGap(26, 26, 26)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_contenedordatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsc_tblusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jp_marcoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaruserActionPerformed
 
        //Declaración de variables y sus respectivos campos
        String nom,user,clave;
        nom = txt_nombre.getText();
        user = txt_user.getText();
        clave = String.valueOf(txt_clave.getPassword());
        int rol = txt_rol.getSelectedIndex();
        
        //Condicional IF que confirma que no hayan campos vacíos
        if ( nom.isEmpty() || user.isEmpty() || clave.isEmpty()){
            
            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos","error", 2);
            
        }else{
        
        //Declaración de consulta
        PreparedStatement ps;
     
        String query;
        //Creación de sentencia SQL para insertar un registro
        query = "INSERT INTO `usuario`(`nombre_usuario`, `clave`, `nombre_empleado`,`cod_rol`) VALUES (?,?,?,?)";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
            
            ps.setString(1, user);
            ps.setString(2, clave);
            ps.setString(3, nom);
            ps.setInt(4, rol);
            
            //Condicional IF que confirma la inserción de un usuario
             if(ps.executeUpdate() > 0)
            {
                JOptionPane.showMessageDialog(null, "Agregado exitosamente!");
                Mostrardatos("");
                Limpiar();
            }
        
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_usuarios.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    }//GEN-LAST:event_btn_agregaruserActionPerformed

    private void tbl_usuariosSeleccionar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_usuariosSeleccionar

        try {
            //Declaración de variables y sus respectivas posiciones en la tabla de usuarios
            String id = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),0);
            String user = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),1);
            String clave = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),2);
            String nom = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),3);
            String rol = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),4);

            txt_nombre.setText(nom);
            txt_user.setText(user);
            txt_clave.setText(clave);

        }
        //Mensaje de error
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_tbl_usuariosSeleccionar

    private void txt_rolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_rolActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void btn_eliminaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminaruserActionPerformed
        // TODO add your handling code here:
        //Declaración de variable y su respectiva posición en la tabla
        String id = (String) usuario.getValueAt(tbl_usuarios.getSelectedRow(),0);

        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia SQL para eliminar un registro dado un código usuario
        String query = "DELETE FROM usuario WHERE ID_usuario=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, id);
            
            //Condicional IF que confirma la eliminación de un usuario
            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "Usuario Eliminado");
                Limpiar();
                Mostrardatos("");
            }
        
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_eliminaruserActionPerformed

    private void btn_editaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editaruserActionPerformed
        // TODO add your handling code here:
        
        //Declaración de variables y sus respectivos campos o posición
        String id = (String)usuario.getValueAt(tbl_usuarios.getSelectedRow(),0);
        String nom = txt_nombre.getText();
        String user = txt_user.getText();
        int rol = txt_rol.getSelectedIndex();
        String clave = String.valueOf(txt_clave.getPassword());
      
      
        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia SQL para actualizar los datos dado un ID de cliente
        String query = "UPDATE usuario SET nombre_usuario=?, clave=?, nombre_empleado=?, cod_rol=? WHERE ID_usuario=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(5, id);
            ps.setString(1, user);
            ps.setString(2, clave);
            ps.setString(3, nom);
            ps.setInt(4, rol);
            
        
            ps.executeUpdate();
            //Mensaje que confirma la actualización del usuario
            JOptionPane.showMessageDialog(null, "Usuario Modificado");
            Limpiar();
            Mostrardatos("");
        
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_editaruserActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        //Método constructor parar el main
        frm_main form = new frm_main();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_control_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_control_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_control_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_control_usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el control de usuarios
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_control_usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregaruser;
    private javax.swing.JButton btn_editaruser;
    private javax.swing.JButton btn_eliminaruser;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel jp_contenedor;
    private javax.swing.JPanel jp_contenedordatos;
    private javax.swing.JPanel jp_des;
    private javax.swing.JPanel jp_desa;
    private javax.swing.JPanel jp_encabezado;
    private javax.swing.JPanel jp_marcoinferior;
    private javax.swing.JPanel jp_marcosuperior;
    private javax.swing.JScrollPane jsc_tblusuarios;
    private javax.swing.JLabel lbl_controlusuario;
    private javax.swing.JLabel lbl_desa;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombreusuario;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_rolusuario;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTable tbl_usuarios;
    private javax.swing.JPasswordField txt_clave;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JComboBox<String> txt_rol;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}