/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_de_control_y_acceso;

import conexion.MyConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Edwin Martinez
 */
public class frm_control_proveedores extends javax.swing.JFrame {
    
     DefaultTableModel proveedor;


    /**
     * Creates new form frm_control_proveedores
     */
    public frm_control_proveedores() {
        initComponents();
        this.proveedor = (DefaultTableModel) tbl_proveedores.getModel();
        Mostrardatos("");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }
    
    public void Limpiar() {
        //Limpia los campos en control de proveedores
        txt_nombreproveedor.setText("");
        txt_direccionproveedor.setText("");
    }
    
    public void RefrescarTabla(){
        //Función encargada de refrescar la tabla utilizando revalidate
        try {
        proveedor.setColumnCount(0);
        proveedor.setRowCount(0);
        tbl_proveedores.revalidate();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
   
          }
    
    public final void Mostrardatos(String valor){
            //Función para llenar la tabla de usuarios desde la base de datos
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
            RefrescarTabla();
            proveedor.addColumn("Código");
            proveedor.addColumn("Nombre");
            proveedor.addColumn("Dirección");
            
            this.tbl_proveedores.setModel(proveedor);
            String sql;
            
            //Condicional IF que selecciona los proveedores
            if (valor.equals(""))
            {
            sql="SELECT * FROM proveedor";
            }
           
            else{
            sql="SELECT * FROM proveedor WHERE cod_prov='"+valor+"'";
            }
            
            //Arreglo para llenar la tabla de proveedores
            String []datos=new String [3];
            try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
   
            proveedor.addRow(datos);
            }
            tbl_proveedores.setModel(proveedor);
            }
            //Mensaje de error
            catch(SQLException ex){
            Logger.getLogger(frm_control_proveedores.class.getName()).log(Level.SEVERE,null,ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedor = new javax.swing.JPanel();
        jp_encabezado = new javax.swing.JPanel();
        lbl_controlusuario = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        jp_contenedordatosprov = new javax.swing.JPanel();
        lbl_nombreproveedor = new javax.swing.JLabel();
        txt_nombreproveedor = new javax.swing.JTextField();
        lbl_direccionproveedor = new javax.swing.JLabel();
        txt_direccionproveedor = new javax.swing.JTextField();
        btn_agregaruser = new javax.swing.JButton();
        btn_editaruser = new javax.swing.JButton();
        btn_eliminaruser = new javax.swing.JButton();
        jsc_tblproveedores = new javax.swing.JScrollPane();
        tbl_proveedores = new javax.swing.JTable();
        jp_marcoinferior = new javax.swing.JPanel();
        jp_marcosuperior = new javax.swing.JPanel();
        btn_regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_contenedor.setBackground(new java.awt.Color(255, 255, 255));

        jp_encabezado.setBackground(new java.awt.Color(255, 255, 255));

        lbl_controlusuario.setFont(new java.awt.Font("Britannic Bold", 1, 28)); // NOI18N
        lbl_controlusuario.setText("CONTROL DE PROVEEDORES");

        lbl_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        javax.swing.GroupLayout jp_encabezadoLayout = new javax.swing.GroupLayout(jp_encabezado);
        jp_encabezado.setLayout(jp_encabezadoLayout);
        jp_encabezadoLayout.setHorizontalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addComponent(lbl_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_controlusuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_encabezadoLayout.setVerticalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_logo))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_encabezadoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_controlusuario)
                .addGap(34, 34, 34))
        );

        jp_contenedordatosprov.setBackground(new java.awt.Color(234, 234, 234));

        lbl_nombreproveedor.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombreproveedor.setText("Nombre");

        txt_nombreproveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nombreproveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreproveedorActionPerformed(evt);
            }
        });

        lbl_direccionproveedor.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_direccionproveedor.setText("Dirección");

        txt_direccionproveedor.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        btn_agregaruser.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        btn_agregaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearusuario_ico.png"))); // NOI18N
        btn_agregaruser.setToolTipText("Registrar Proveedor");
        btn_agregaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregaruserActionPerformed(evt);
            }
        });

        btn_editaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificarusuario_ico.png"))); // NOI18N
        btn_editaruser.setToolTipText("Editar Proveedor");
        btn_editaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editaruserActionPerformed(evt);
            }
        });

        btn_eliminaruser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminarusuario_ico.png"))); // NOI18N
        btn_eliminaruser.setToolTipText("Eliminar Proveedor");
        btn_eliminaruser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminaruserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedordatosprovLayout = new javax.swing.GroupLayout(jp_contenedordatosprov);
        jp_contenedordatosprov.setLayout(jp_contenedordatosprovLayout);
        jp_contenedordatosprovLayout.setHorizontalGroup(
            jp_contenedordatosprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatosprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                        .addComponent(lbl_nombreproveedor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                                .addComponent(btn_agregaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_editaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(btn_eliminaruser, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                                .addComponent(lbl_direccionproveedor)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt_nombreproveedor)
                            .addComponent(txt_direccionproveedor))
                        .addContainerGap())))
        );
        jp_contenedordatosprovLayout.setVerticalGroup(
            jp_contenedordatosprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosprovLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombreproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_direccionproveedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_direccionproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addGroup(jp_contenedordatosprovLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_editaruser)
                    .addComponent(btn_agregaruser)
                    .addComponent(btn_eliminaruser))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tbl_proveedores.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tbl_proveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_proveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_proveedoresSeleccionar(evt);
            }
        });
        jsc_tblproveedores.setViewportView(tbl_proveedores);

        jp_marcoinferior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcoinferiorLayout = new javax.swing.GroupLayout(jp_marcoinferior);
        jp_marcoinferior.setLayout(jp_marcoinferiorLayout);
        jp_marcoinferiorLayout.setHorizontalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcoinferiorLayout.setVerticalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        jp_marcosuperior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcosuperiorLayout = new javax.swing.GroupLayout(jp_marcosuperior);
        jp_marcosuperior.setLayout(jp_marcosuperiorLayout);
        jp_marcosuperiorLayout.setHorizontalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcosuperiorLayout.setVerticalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        btn_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/regresar_ico.png"))); // NOI18N
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedorLayout = new javax.swing.GroupLayout(jp_contenedor);
        jp_contenedor.setLayout(jp_contenedorLayout);
        jp_contenedorLayout.setHorizontalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_marcosuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_marcoinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_regresar))
                    .addGroup(jp_contenedorLayout.createSequentialGroup()
                        .addComponent(jp_contenedordatosprov, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jsc_tblproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jp_contenedorLayout.setVerticalGroup(
            jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorLayout.createSequentialGroup()
                .addComponent(jp_marcosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_regresar))
                .addGap(33, 33, 33)
                .addGroup(jp_contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_contenedordatosprov, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jsc_tblproveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jp_marcoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreproveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreproveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreproveedorActionPerformed

    private void btn_agregaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregaruserActionPerformed
        
        //Declaración de variables y sus respectivos campos
        String nom,direc;
        nom = txt_nombreproveedor.getText();
        direc = txt_direccionproveedor.getText();
  
        //Condicional IF para confirmar que hayan campos vacíos
        if ( nom.isEmpty() || direc.isEmpty() ){

            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos","error", 2);

        }else{
            
            //Declaración de consulta
            PreparedStatement ps;
            String query;
            //Creación de sentencia SQL para insertar los registros en la base de datos
            query = "INSERT INTO `proveedor`(`nom_prov`, `direccion_prov`) VALUES (?,?)";
            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, nom);
                ps.setString(2, direc);
                
                //Condicional IF para validad la inserción de los registros
                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Agregado exitosamente!");
                    Mostrardatos("");
                    Limpiar();
                }
            
            //Mensaje de error
            } catch (SQLException ex) {
                Logger.getLogger(frm_control_usuarios.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    }//GEN-LAST:event_btn_agregaruserActionPerformed

    private void btn_editaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editaruserActionPerformed
        // TODO add your handling code here
        
        //Declaración de variables y sus respectivos campos
        String cod = (String)proveedor.getValueAt(tbl_proveedores.getSelectedRow(),0);
        String nom = txt_nombreproveedor.getText();
        String direc = txt_direccionproveedor.getText();
        
        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia para actualizar los registros en la base de datos dado un código de proveedor
        String query = "UPDATE proveedor SET nom_prov=?, direccion_prov=? WHERE cod_prov=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(3, cod);
            ps.setString(1, nom);
            ps.setString(2, direc);
           

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proveedor Modificado");
            Limpiar();
            Mostrardatos("");
        
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_medicamentos.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_editaruserActionPerformed

    private void btn_eliminaruserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminaruserActionPerformed
        // TODO add your handling code here:
        //Declaración de variable y su respectivo campo
        String cod = (String) proveedor.getValueAt(tbl_proveedores.getSelectedRow(),0);

        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia SQL para eliminar registros dado un código de proveedor
        String query = "DELETE FROM proveedor WHERE cod_prov=?";
        try {
            ps = MyConnection.getConnection().prepareStatement(query);

            ps.setString(1, cod);
            
            //Mensaje para confirmar la eliminación del registro
            if(ps.executeUpdate() > 0)
            {

                JOptionPane.showMessageDialog(null, "Proveedor Eliminado");
                Limpiar();
                Mostrardatos("");
            }
        
        //Mensaje de error
        } catch (SQLException ex) {
            Logger.getLogger(frm_control_proveedores.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_btn_eliminaruserActionPerformed

    private void tbl_proveedoresSeleccionar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_proveedoresSeleccionar

        try {
            
            //Declaración de variables y sus respectivos campos
            String cod = (String) proveedor.getValueAt(tbl_proveedores.getSelectedRow(),0);
            String nom = (String) proveedor.getValueAt(tbl_proveedores.getSelectedRow(),1);
            String direc = (String) proveedor.getValueAt(tbl_proveedores.getSelectedRow(),2);
           
            
            txt_nombreproveedor.setText(nom);
            txt_direccionproveedor.setText(direc);

        }
        
        //Mensaje de error
        catch (Exception ex){
            JOptionPane.showMessageDialog(null, "error "+ex);
        }
    }//GEN-LAST:event_tbl_proveedoresSeleccionar

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        //Método constructor para el main
        frm_main form = new frm_main();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_control_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_control_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_control_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_control_proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el control de proveedores
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_control_proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregaruser;
    private javax.swing.JButton btn_editaruser;
    private javax.swing.JButton btn_eliminaruser;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JPanel jp_contenedor;
    private javax.swing.JPanel jp_contenedordatosprov;
    private javax.swing.JPanel jp_encabezado;
    private javax.swing.JPanel jp_marcoinferior;
    private javax.swing.JPanel jp_marcosuperior;
    private javax.swing.JScrollPane jsc_tblproveedores;
    private javax.swing.JLabel lbl_controlusuario;
    private javax.swing.JLabel lbl_direccionproveedor;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nombreproveedor;
    private javax.swing.JTable tbl_proveedores;
    private javax.swing.JTextField txt_direccionproveedor;
    private javax.swing.JTextField txt_nombreproveedor;
    // End of variables declaration//GEN-END:variables
}
