/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios_de_control_y_acceso;

import facturacion.frm_buscar_medicamentos;
import facturacion.frm_facturacion_medicamentos;
import static facturacion.frm_facturacion_medicamentos.txt_nombreempleadomedic;

/**
 *
 * @author Edwin Martinez
 */
public class frm_main extends javax.swing.JFrame {

    public static String nom_emp;
    
    public frm_main() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedormain = new javax.swing.JPanel();
        lbl_desa = new javax.swing.JLabel();
        jp_contenedorbotones = new javax.swing.JPanel();
        btn_controlusuarios = new javax.swing.JButton();
        btn_controlproveedores = new javax.swing.JButton();
        btn_controlmedicamentos = new javax.swing.JButton();
        btn_facturacion = new javax.swing.JButton();
        btn_controldeclientes = new javax.swing.JButton();
        lbl_logotransparente = new javax.swing.JLabel();
        btn_cerrarsesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_contenedormain.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedorbotones.setBackground(new java.awt.Color(0, 152, 108));

        btn_controlusuarios.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_controlusuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controlusuarios_ico.png"))); // NOI18N
        btn_controlusuarios.setText("Control De Usuarios");
        btn_controlusuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlusuariosActionPerformed(evt);
            }
        });

        btn_controlproveedores.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_controlproveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controlproveedores_ico.png"))); // NOI18N
        btn_controlproveedores.setText("Control De Proveedores");
        btn_controlproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlproveedoresActionPerformed(evt);
            }
        });

        btn_controlmedicamentos.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_controlmedicamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controlmedicamentos_ico.png"))); // NOI18N
        btn_controlmedicamentos.setText("Control de Medicamentos");
        btn_controlmedicamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controlmedicamentosActionPerformed(evt);
            }
        });

        btn_facturacion.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facturacion_ico.png"))); // NOI18N
        btn_facturacion.setText("Facturación");
        btn_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturacionActionPerformed(evt);
            }
        });

        btn_controldeclientes.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_controldeclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controlclientes_Ico.png"))); // NOI18N
        btn_controldeclientes.setText("Control De Clientes");
        btn_controldeclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_controldeclientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedorbotonesLayout = new javax.swing.GroupLayout(jp_contenedorbotones);
        jp_contenedorbotones.setLayout(jp_contenedorbotonesLayout);
        jp_contenedorbotonesLayout.setHorizontalGroup(
            jp_contenedorbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorbotonesLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jp_contenedorbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_controlmedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_controldeclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_controlproveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_controlusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_facturacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jp_contenedorbotonesLayout.setVerticalGroup(
            jp_contenedorbotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedorbotonesLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_controlusuarios)
                .addGap(40, 40, 40)
                .addComponent(btn_controlproveedores)
                .addGap(40, 40, 40)
                .addComponent(btn_controldeclientes)
                .addGap(40, 40, 40)
                .addComponent(btn_controlmedicamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btn_facturacion)
                .addGap(55, 55, 55))
        );

        lbl_logotransparente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo_transparent.png"))); // NOI18N

        btn_cerrarsesion.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion_ico.png"))); // NOI18N
        btn_cerrarsesion.setText("Cerrar Sesión");
        btn_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedormainLayout = new javax.swing.GroupLayout(jp_contenedormain);
        jp_contenedormain.setLayout(jp_contenedormainLayout);
        jp_contenedormainLayout.setHorizontalGroup(
            jp_contenedormainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedormainLayout.createSequentialGroup()
                .addGroup(jp_contenedormainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedormainLayout.createSequentialGroup()
                        .addContainerGap(31, Short.MAX_VALUE)
                        .addGroup(jp_contenedormainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jp_contenedormainLayout.createSequentialGroup()
                                .addComponent(lbl_desa)
                                .addGap(1283, 1283, 1283))
                            .addGroup(jp_contenedormainLayout.createSequentialGroup()
                                .addComponent(lbl_logotransparente)
                                .addGap(356, 356, 356))))
                    .addGroup(jp_contenedormainLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btn_cerrarsesion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jp_contenedorbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_contenedormainLayout.setVerticalGroup(
            jp_contenedormainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedormainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_desa)
                .addGap(158, 158, 158)
                .addComponent(lbl_logotransparente)
                .addGap(93, 93, 93)
                .addComponent(btn_cerrarsesion)
                .addGap(27, 27, 27))
            .addGroup(jp_contenedormainLayout.createSequentialGroup()
                .addComponent(jp_contenedorbotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedormain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_contenedormain, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_controlusuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlusuariosActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para el control de usuarios
        frm_control_usuarios form = new frm_control_usuarios();
      
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_controlusuariosActionPerformed

    private void btn_controlproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlproveedoresActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para el control de proveedores
        frm_control_proveedores form = new frm_control_proveedores();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_controlproveedoresActionPerformed

    private void btn_controldeclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controldeclientesActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para el control de clientes
        frm_control_clientes form = new frm_control_clientes();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_controldeclientesActionPerformed

    private void btn_controlmedicamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_controlmedicamentosActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para el control de medicamentos
        frm_control_medicamentos form = new frm_control_medicamentos();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_controlmedicamentosActionPerformed

    private void btn_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturacionActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para la facturación de medicamentos
        frm_facturacion_medicamentos form = new frm_facturacion_medicamentos();
        form.setVisible(true);
        txt_nombreempleadomedic.setText(nom_emp);
        this.dispose();
    }//GEN-LAST:event_btn_facturacionActionPerformed

    private void btn_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsesionActionPerformed
        // TODO add your handling code here:
        
        //Método constructor para el login
        frm_login form = new frm_login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el main
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarsesion;
    private javax.swing.JButton btn_controldeclientes;
    private javax.swing.JButton btn_controlmedicamentos;
    private javax.swing.JButton btn_controlproveedores;
    private javax.swing.JButton btn_controlusuarios;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JPanel jp_contenedorbotones;
    private javax.swing.JPanel jp_contenedormain;
    private javax.swing.JLabel lbl_desa;
    private javax.swing.JLabel lbl_logotransparente;
    // End of variables declaration//GEN-END:variables
}
