/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import conexion.MyConnection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Edwin Martinez
 */
public class frm_registrar_cliente extends javax.swing.JFrame {

    /**
     * Creates new form frm_registrar_cliente
     */
    public frm_registrar_cliente() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_datosusuario = new javax.swing.JPanel();
        lbl_nombrecliente = new javax.swing.JLabel();
        txt_nombrecliente = new javax.swing.JTextField();
        lbl_sexo = new javax.swing.JLabel();
        txt_apellidoscliente = new javax.swing.JTextField();
        lbl_cedula = new javax.swing.JLabel();
        btn_agregarcliente = new javax.swing.JButton();
        txt_cedulacliente = new javax.swing.JTextField();
        lbl_user = new javax.swing.JLabel();
        txt_sexocliente = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_datosusuario.setBackground(new java.awt.Color(255, 255, 255));
        jp_datosusuario.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        lbl_nombrecliente.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombrecliente.setText("Nombre");

        txt_nombrecliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txt_nombrecliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreclienteActionPerformed(evt);
            }
        });

        lbl_sexo.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_sexo.setText("Sexo");

        txt_apellidoscliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_cedula.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_cedula.setText("Cédula");
        lbl_cedula.setToolTipText("");

        btn_agregarcliente.setFont(new java.awt.Font("Britannic Bold", 0, 16)); // NOI18N
        btn_agregarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/crearusuario_ico.png"))); // NOI18N
        btn_agregarcliente.setText("Registrar");
        btn_agregarcliente.setToolTipText("Registrar Cliente");
        btn_agregarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarclienteActionPerformed(evt);
            }
        });

        txt_cedulacliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        lbl_user.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_user.setText("Apellidos");

        txt_sexocliente.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jp_datosusuarioLayout = new javax.swing.GroupLayout(jp_datosusuario);
        jp_datosusuario.setLayout(jp_datosusuarioLayout);
        jp_datosusuarioLayout.setHorizontalGroup(
            jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_datosusuarioLayout.createSequentialGroup()
                        .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombrecliente)
                            .addComponent(txt_apellidoscliente)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_datosusuarioLayout.createSequentialGroup()
                                .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_cedula)
                                    .addComponent(txt_cedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txt_sexocliente)
                                    .addComponent(lbl_sexo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(jp_datosusuarioLayout.createSequentialGroup()
                        .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombrecliente)
                            .addComponent(lbl_user))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jp_datosusuarioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_agregarcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_datosusuarioLayout.setVerticalGroup(
            jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_datosusuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_nombrecliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombrecliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lbl_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_apellidoscliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_cedula)
                    .addComponent(lbl_sexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_datosusuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cedulacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexocliente, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btn_agregarcliente)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_datosusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_datosusuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nombreclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreclienteActionPerformed

    private void btn_agregarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarclienteActionPerformed
        
        //Declaración de variables y asignación de campos
        String nom,ape,ced,sex;
        nom = txt_nombrecliente.getText();
        ape = txt_apellidoscliente.getText();
        ced = txt_cedulacliente.getText();
        sex = txt_sexocliente.getText();
 
        //Condicional IF que confirma que no haya campos vacíos
        if ( nom.isEmpty() || ape.isEmpty() || ced.isEmpty() || sex.isEmpty()){

            JOptionPane.showMessageDialog(null, "Por favor, llene todos los campos","error", 2);

        }else{
            
            //Declaración de consulta
            PreparedStatement ps;
            String query;
            
            //Creación de sentencia SQL para insertar los datos del cliente en la base de datos
            query = "INSERT INTO `cliente`(`nom_cliente`, `apellidos_cliente`, `cedula_cliente`,`sexo_cliente`) VALUES (?,?,?,?)";
            try {
                ps = MyConnection.getConnection().prepareStatement(query);

                ps.setString(1, nom);
                ps.setString(2, ape);
                ps.setString(3, ced);
                ps.setString(4, sex);
                
                //Condicional IF que confirma la inserción de los datos
                if(ps.executeUpdate() > 0)
                {
                    JOptionPane.showMessageDialog(null, "Agregado exitosamente!");
                    this.dispose();
                }

            } 
            //Mensaje de error
            catch (SQLException ex) {
                Logger.getLogger(frm_registrar_cliente.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "error "+ex);
            }
        }
    }//GEN-LAST:event_btn_agregarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_registrar_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar el formulario de registro de clientes
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_registrar_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregarcliente;
    private javax.swing.JPanel jp_datosusuario;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_nombrecliente;
    private javax.swing.JLabel lbl_sexo;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JTextField txt_apellidoscliente;
    private javax.swing.JTextField txt_cedulacliente;
    private javax.swing.JTextField txt_nombrecliente;
    private javax.swing.JTextField txt_sexocliente;
    // End of variables declaration//GEN-END:variables
}
