/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package facturacion;

import java.util.Date;
import conexion.MyConnection;
import static facturacion.facturacion_medicamentos_clases.guardar;
import static facturacion.facturacion_medicamentos_clases.monto;
import static facturacion.facturacion_medicamentos_clases.suma;
import formularios_de_control_y_acceso.frm_login;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Edwin Martinez
 */
public class frm_facturacion_medicamentos extends javax.swing.JFrame {
    
    
     DefaultTableModel detalles;
     
    /**
     * Creates new form frm_facturacion
     */
 
   
    int lastid;
    Statement st;
    ResultSet rs;
    
    public void getlastid()
    {
        try{
            Connection con = MyConnection.getConnection();
            String sql = "select max(no_factura) from factura_medicamento";
            st= con.createStatement();
            
            rs=st.executeQuery(sql);
            
            //Condicional IF que genera el nuevo No. de factura
            if(rs.next()){
                lastid = rs.getInt(1);
                lastid++;
                frm_facturacion_medicamentos.txt_nofacturamedic.setText(Integer.toString(lastid));
            }
            else{
                
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(facturacion_medicamentos_clases.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public final void imprimir(){
        //Imprime la factura
        Connection cn=MyConnection.getConnection();
        try{
          int txtFac;
          JasperReport jr = (JasperReport) JRLoader.loadObject(frm_facturacion_medicamentos.class.getResource("/facturacion/reporte_facturacion.jasper"));
          Map parametros = new HashMap<>();
          parametros.put("factura",txtFac = Integer.parseInt(txt_nofacturamedic.getText()));
          JasperPrint jp = JasperFillManager.fillReport(jr, parametros, cn);
          JasperViewer jv = new JasperViewer(jp, false);
          jv.setVisible(true); 
        }
        catch (JRException ex) {
            JOptionPane.showMessageDialog(rootPane, ex);
        }
}
  
    public frm_facturacion_medicamentos() {
        initComponents();
        this.detalles = (DefaultTableModel) tbl_factura_medicamentos.getModel();
        this.setResizable(false);
        Mostrardatos("");
        getlastid();
        txt_fechafacturamedic.setText(fechaActual());
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    }

     public final void Mostrardatos(String valor){
           
          //Muestra los datos en la tabla de factura
            MyConnection cc=new MyConnection();
            Connection cn=MyConnection.getConnection();
          
            detalles.addColumn("Código");
            detalles.addColumn("Nombre");
            detalles.addColumn("Precio");
            detalles.addColumn("Cantidad");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
     //Este es el metodo que se usa para limpiar la tabla
     
    public  void LimpiarTabla() {
        //Ciclo FOR que limpia la tabla
        for (int i = 0; i < detalles.getRowCount(); i++) {
            detalles.removeRow(i);
            i = i - 1;
        }
    }
    @SuppressWarnings("unchecked")
    
    public static String fechaActual(){
        //Toma la fecha de forma automática
        Date fecha = new Date();
        SimpleDateFormat formatoFecha=new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        
        return formatoFecha.format(fecha);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_des = new javax.swing.JLabel();
        lbl_nom = new javax.swing.JLabel();
        jp_desa = new javax.swing.JPanel();
        jp_marcosuperior = new javax.swing.JPanel();
        lbl_logomedicamento = new javax.swing.JLabel();
        lbl_facturacionmedicamento = new javax.swing.JLabel();
        jp_marcoinferior = new javax.swing.JPanel();
        jp_contenedordatosfactura = new javax.swing.JPanel();
        lbl_nombremedic = new javax.swing.JLabel();
        txt_nombremedic = new javax.swing.JTextField();
        lbl_codigomedic = new javax.swing.JLabel();
        lbl_cantidadmedic = new javax.swing.JLabel();
        lbl_preciomedic = new javax.swing.JLabel();
        txt_cantidadmedic = new javax.swing.JTextField();
        btn_agregarproducto = new javax.swing.JButton();
        jsc_tblfactura = new javax.swing.JScrollPane();
        tbl_factura_medicamentos = new javax.swing.JTable();
        btn_removerproducto = new javax.swing.JButton();
        btn_nuevafacturamedic = new javax.swing.JButton();
        btn_guardareimprimirfacturamedic = new javax.swing.JButton();
        lbl_montototalfacturamedic = new javax.swing.JLabel();
        txt_montototalfacturamedic = new javax.swing.JTextField();
        txt_preciomedic = new javax.swing.JTextField();
        txt_codigomedic = new javax.swing.JTextField();
        btn_vertodoslosproductos = new javax.swing.JButton();
        txt_montomedic = new javax.swing.JTextField();
        lbl_montomedic = new javax.swing.JLabel();
        jp_contenedordatos = new javax.swing.JPanel();
        jp_contenedordatosgen = new javax.swing.JPanel();
        lbl_datosgeneralesmedic = new javax.swing.JLabel();
        lbl_nofacturamedicamento = new javax.swing.JLabel();
        lbl_fechafacturamedic = new javax.swing.JLabel();
        txt_nofacturamedic = new javax.swing.JTextField();
        txt_fechafacturamedic = new javax.swing.JTextField();
        jp_contenedoratendidopor = new javax.swing.JPanel();
        lbl_atendidopormedic = new javax.swing.JLabel();
        lbl_nombrempleadomedic = new javax.swing.JLabel();
        txt_nombreempleadomedic = new javax.swing.JTextField();
        jp_contenedordatoscli = new javax.swing.JPanel();
        lbl_datosclientemedic = new javax.swing.JLabel();
        txt_idclientemedic = new javax.swing.JTextField();
        lbl_idclientemedic = new javax.swing.JLabel();
        lbl_nombreclientemedic = new javax.swing.JLabel();
        txt_nombreclientemedic = new javax.swing.JTextField();
        lbl_apellidosclientemedic = new javax.swing.JLabel();
        txt_apellidosclientemedic = new javax.swing.JTextField();
        btn_buscarclientemedic = new javax.swing.JButton();
        btn_registrarcliente = new javax.swing.JButton();
        btn_cerrarsesion = new javax.swing.JButton();

        lbl_des.setFont(new java.awt.Font("Britannic Bold", 1, 28)); // NOI18N
        lbl_des.setText("CONTROL DE MEDICAMENTOS");

        lbl_nom.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nom.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nom.setText("Nombre");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_desa.setBackground(new java.awt.Color(255, 255, 255));

        jp_marcosuperior.setBackground(new java.awt.Color(0, 152, 108));

        lbl_logomedicamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N

        lbl_facturacionmedicamento.setFont(new java.awt.Font("Britannic Bold", 1, 28)); // NOI18N
        lbl_facturacionmedicamento.setForeground(new java.awt.Color(255, 255, 255));
        lbl_facturacionmedicamento.setText("FACTURACIÓN DE MEDICAMENTOS");

        javax.swing.GroupLayout jp_marcosuperiorLayout = new javax.swing.GroupLayout(jp_marcosuperior);
        jp_marcosuperior.setLayout(jp_marcosuperiorLayout);
        jp_marcosuperiorLayout.setHorizontalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_marcosuperiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_logomedicamento)
                .addGap(18, 18, 18)
                .addComponent(lbl_facturacionmedicamento)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_marcosuperiorLayout.setVerticalGroup(
            jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_marcosuperiorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_marcosuperiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_marcosuperiorLayout.createSequentialGroup()
                        .addComponent(lbl_logomedicamento)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_marcosuperiorLayout.createSequentialGroup()
                        .addComponent(lbl_facturacionmedicamento)
                        .addGap(46, 46, 46))))
        );

        jp_marcoinferior.setBackground(new java.awt.Color(0, 152, 108));

        javax.swing.GroupLayout jp_marcoinferiorLayout = new javax.swing.GroupLayout(jp_marcoinferior);
        jp_marcoinferior.setLayout(jp_marcoinferiorLayout);
        jp_marcoinferiorLayout.setHorizontalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jp_marcoinferiorLayout.setVerticalGroup(
            jp_marcoinferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jp_contenedordatosfactura.setBackground(new java.awt.Color(234, 234, 234));

        lbl_nombremedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombremedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombremedic.setText("Nombre ");

        txt_nombremedic.setEditable(false);

        lbl_codigomedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_codigomedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_codigomedic.setText("Código");

        lbl_cantidadmedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_cantidadmedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_cantidadmedic.setText("Cant.");

        lbl_preciomedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_preciomedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_preciomedic.setText("Precio");

        txt_cantidadmedic.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_cantidadmedicKeyPressed(evt);
            }
        });

        btn_agregarproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/añadirproducto_icon.png"))); // NOI18N
        btn_agregarproducto.setToolTipText("Agregar producto");
        btn_agregarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarproductoActionPerformed(evt);
            }
        });

        tbl_factura_medicamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jsc_tblfactura.setViewportView(tbl_factura_medicamentos);

        btn_removerproducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/removerproducto_ico.png"))); // NOI18N
        btn_removerproducto.setToolTipText("Remover producto");
        btn_removerproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerproductoActionPerformed(evt);
            }
        });

        btn_nuevafacturamedic.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        btn_nuevafacturamedic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevafactura_ico.png"))); // NOI18N
        btn_nuevafacturamedic.setToolTipText("Nueva factura");
        btn_nuevafacturamedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevafacturamedicActionPerformed(evt);
            }
        });

        btn_guardareimprimirfacturamedic.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        btn_guardareimprimirfacturamedic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardareimprimir_ico.png"))); // NOI18N
        btn_guardareimprimirfacturamedic.setToolTipText("Guardar e Imprimir ");
        btn_guardareimprimirfacturamedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardareimprimirfacturamedicActionPerformed(evt);
            }
        });

        lbl_montototalfacturamedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_montototalfacturamedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_montototalfacturamedic.setText("TOTAL");

        txt_montototalfacturamedic.setEditable(false);
        txt_montototalfacturamedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montototalfacturamedicActionPerformed(evt);
            }
        });

        txt_preciomedic.setEditable(false);

        txt_codigomedic.setEditable(false);

        btn_vertodoslosproductos.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_vertodoslosproductos.setText("Ver todos los medicamentos");
        btn_vertodoslosproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vertodoslosproductosActionPerformed(evt);
            }
        });

        txt_montomedic.setEditable(false);
        txt_montomedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_montomedicActionPerformed(evt);
            }
        });

        lbl_montomedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_montomedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_montomedic.setText("Monto");

        javax.swing.GroupLayout jp_contenedordatosfacturaLayout = new javax.swing.GroupLayout(jp_contenedordatosfactura);
        jp_contenedordatosfactura.setLayout(jp_contenedordatosfacturaLayout);
        jp_contenedordatosfacturaLayout.setHorizontalGroup(
            jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_vertodoslosproductos)
                    .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addComponent(btn_nuevafacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_guardareimprimirfacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_codigomedic)
                                    .addComponent(lbl_montomedic))
                                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(txt_codigomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(lbl_nombremedic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_nombremedic, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_montomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_montototalfacturamedic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_montototalfacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lbl_cantidadmedic)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cantidadmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosfacturaLayout.createSequentialGroup()
                                        .addComponent(btn_agregarproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_removerproducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                        .addComponent(lbl_preciomedic)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_preciomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jsc_tblfactura))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jp_contenedordatosfacturaLayout.setVerticalGroup(
            jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_codigomedic)
                            .addComponent(txt_codigomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_cantidadmedic)
                            .addComponent(txt_cantidadmedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombremedic)
                            .addComponent(txt_nombremedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_preciomedic)
                            .addComponent(txt_preciomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_montomedic)
                                    .addComponent(txt_montomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(24, 24, 24)
                                .addComponent(btn_vertodoslosproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosfacturaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_agregarproducto))))
                    .addComponent(btn_removerproducto))
                .addGap(18, 18, 18)
                .addComponent(jsc_tblfactura, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosfacturaLayout.createSequentialGroup()
                            .addGroup(jp_contenedordatosfacturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_montototalfacturamedic)
                                .addComponent(txt_montototalfacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosfacturaLayout.createSequentialGroup()
                            .addComponent(btn_guardareimprimirfacturamedic)
                            .addContainerGap()))
                    .addComponent(btn_nuevafacturamedic)))
        );

        btn_guardareimprimirfacturamedic.getAccessibleContext().setAccessibleName("Guardar ");

        jp_contenedordatos.setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedordatosgen.setBackground(new java.awt.Color(234, 234, 234));
        jp_contenedordatosgen.setForeground(new java.awt.Color(234, 234, 234));

        lbl_datosgeneralesmedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_datosgeneralesmedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_datosgeneralesmedic.setText("DATOS GENERALES");

        lbl_nofacturamedicamento.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nofacturamedicamento.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nofacturamedicamento.setText("No. Factura");

        lbl_fechafacturamedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_fechafacturamedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_fechafacturamedic.setText("Fecha");

        txt_nofacturamedic.setEditable(false);
        txt_nofacturamedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nofacturamedicActionPerformed(evt);
            }
        });

        txt_fechafacturamedic.setEditable(false);

        javax.swing.GroupLayout jp_contenedordatosgenLayout = new javax.swing.GroupLayout(jp_contenedordatosgen);
        jp_contenedordatosgen.setLayout(jp_contenedordatosgenLayout);
        jp_contenedordatosgenLayout.setHorizontalGroup(
            jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosgenLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txt_nofacturamedic, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_nofacturamedicamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatosgenLayout.createSequentialGroup()
                        .addComponent(lbl_fechafacturamedic)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_fechafacturamedic))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosgenLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_datosgeneralesmedic)
                .addGap(96, 96, 96))
        );
        jp_contenedordatosgenLayout.setVerticalGroup(
            jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosgenLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lbl_datosgeneralesmedic)
                .addGap(18, 18, 18)
                .addGroup(jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nofacturamedicamento)
                    .addComponent(lbl_fechafacturamedic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_contenedordatosgenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nofacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fechafacturamedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jp_contenedoratendidopor.setBackground(new java.awt.Color(234, 234, 234));

        lbl_atendidopormedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_atendidopormedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_atendidopormedic.setText("ATENDIDO POR");

        lbl_nombrempleadomedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombrempleadomedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombrempleadomedic.setText("Nombre");

        txt_nombreempleadomedic.setEditable(false);
        txt_nombreempleadomedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreempleadomedicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedoratendidoporLayout = new javax.swing.GroupLayout(jp_contenedoratendidopor);
        jp_contenedoratendidopor.setLayout(jp_contenedoratendidoporLayout);
        jp_contenedoratendidoporLayout.setHorizontalGroup(
            jp_contenedoratendidoporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedoratendidoporLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedoratendidoporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombreempleadomedic)
                    .addGroup(jp_contenedoratendidoporLayout.createSequentialGroup()
                        .addGroup(jp_contenedoratendidoporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_nombrempleadomedic)
                            .addGroup(jp_contenedoratendidoporLayout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(lbl_atendidopormedic)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jp_contenedoratendidoporLayout.setVerticalGroup(
            jp_contenedoratendidoporLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedoratendidoporLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_atendidopormedic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_nombrempleadomedic)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_nombreempleadomedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(188, 188, 188))
        );

        jp_contenedordatoscli.setBackground(new java.awt.Color(234, 234, 234));

        lbl_datosclientemedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_datosclientemedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_datosclientemedic.setText("DATOS DEL CLIENTE");

        txt_idclientemedic.setEditable(false);

        lbl_idclientemedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_idclientemedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_idclientemedic.setText("ID cliente");

        lbl_nombreclientemedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_nombreclientemedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_nombreclientemedic.setText("Nombre");

        txt_nombreclientemedic.setEditable(false);

        lbl_apellidosclientemedic.setBackground(new java.awt.Color(255, 255, 255));
        lbl_apellidosclientemedic.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        lbl_apellidosclientemedic.setText("Apellidos");

        txt_apellidosclientemedic.setEditable(false);

        btn_buscarclientemedic.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscarclientemedic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscarcliente_ico.png"))); // NOI18N
        btn_buscarclientemedic.setToolTipText("Buscar Cliente");
        btn_buscarclientemedic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarclientemedicActionPerformed(evt);
            }
        });

        btn_registrarcliente.setBackground(new java.awt.Color(255, 255, 255));
        btn_registrarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registrarcliente_ico.png"))); // NOI18N
        btn_registrarcliente.setToolTipText("Agregar Nuevo Cliente");
        btn_registrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarclienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_contenedordatoscliLayout = new javax.swing.GroupLayout(jp_contenedordatoscli);
        jp_contenedordatoscli.setLayout(jp_contenedordatoscliLayout);
        jp_contenedordatoscliLayout.setHorizontalGroup(
            jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_nombreclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_nombreclientemedic))
                        .addGap(18, 18, 18)
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_apellidosclientemedic)
                            .addComponent(txt_apellidosclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 1, Short.MAX_VALUE))
                    .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                                .addComponent(lbl_idclientemedic)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_idclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatoscliLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lbl_datosclientemedic)
                                .addGap(46, 46, 46)))
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_buscarclientemedic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_registrarcliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jp_contenedordatoscliLayout.setVerticalGroup(
            jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                        .addComponent(lbl_datosclientemedic)
                        .addGap(21, 21, 21)
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_idclientemedic)
                            .addComponent(txt_idclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_apellidosclientemedic)
                            .addComponent(lbl_nombreclientemedic)))
                    .addGroup(jp_contenedordatoscliLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btn_buscarclientemedic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_registrarcliente)
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addGroup(jp_contenedordatoscliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nombreclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_apellidosclientemedic, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jp_contenedordatosLayout = new javax.swing.GroupLayout(jp_contenedordatos);
        jp_contenedordatos.setLayout(jp_contenedordatosLayout);
        jp_contenedordatosLayout.setHorizontalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addGroup(jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_contenedordatosgen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jp_contenedoratendidopor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_contenedordatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jp_contenedordatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jp_contenedordatosLayout.setVerticalGroup(
            jp_contenedordatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedordatosLayout.createSequentialGroup()
                .addComponent(jp_contenedordatosgen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jp_contenedoratendidopor, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jp_contenedordatoscli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn_cerrarsesion.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btn_cerrarsesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrarsesion_ico.png"))); // NOI18N
        btn_cerrarsesion.setText("Cerrar Sesión");
        btn_cerrarsesion.setActionCommand("");
        btn_cerrarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarsesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_desaLayout = new javax.swing.GroupLayout(jp_desa);
        jp_desa.setLayout(jp_desaLayout);
        jp_desaLayout.setHorizontalGroup(
            jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_marcoinferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jp_marcosuperior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jp_desaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cerrarsesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addComponent(jp_contenedordatosfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jp_desaLayout.setVerticalGroup(
            jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_desaLayout.createSequentialGroup()
                .addComponent(jp_marcosuperior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jp_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jp_contenedordatosfactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_desaLayout.createSequentialGroup()
                        .addComponent(jp_contenedordatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_cerrarsesion)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jp_marcoinferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_desa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_desa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_nofacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nofacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nofacturaActionPerformed

    private void btn_vertodoslosproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vertodoslosproductosActionPerformed
        // TODO add your handling code here:
        frm_buscar_medicamentos medic= new frm_buscar_medicamentos();
        medic.setVisible(true);
    }//GEN-LAST:event_btn_vertodoslosproductosActionPerformed

    private void btn_nuevafacturamedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevafacturamedicActionPerformed
        // Muestra nuevamente los campos en blanco
        
        //Muestra los campos en blanco en facturación
        txt_idclientemedic.setText("");
        txt_nombreclientemedic.setText("");
        txt_apellidosclientemedic.setText("");
        txt_codigomedic.setText("");
        txt_preciomedic.setText("");
        txt_nombremedic.setText("");
        txt_montototalfacturamedic.setText("");
        txt_montomedic.setText("");
        txt_nofacturamedic.setText("");
        txt_fechafacturamedic.setText(fechaActual());
        txt_nofacturamedic.setText("");
         
        LimpiarTabla();
        getlastid();
    }//GEN-LAST:event_btn_nuevafacturamedicActionPerformed

    private void btn_guardareimprimirfacturamedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardareimprimirfacturamedicActionPerformed
        // TODO add your handling code here:
        String detalle = txt_nofacturamedic.getText();
        
        for (int i=0; i<tbl_factura_medicamentos.getRowCount();i++){
        
        //Declaración de consulta
        PreparedStatement ps;
        
        //Creación de sentencia SQL para insertar los datos en detalle_factura_medicamentos
        String query = "INSERT INTO `detalle_factura_medicamento`(`no_detallefactura`,`cod_medic`, `nom_medic`,`precio_unidad`,`cant_medic`) VALUES (?,?,?,?,?)";
        
        try {
            ps = MyConnection.getConnection().prepareStatement(query);
              
            ps.setString(1, detalle);
    
          ps.setString(2, tbl_factura_medicamentos.getValueAt(i, 0).toString());
          ps.setString(3, tbl_factura_medicamentos.getValueAt(i, 1).toString());
          ps.setString(4, tbl_factura_medicamentos.getValueAt(i, 2).toString());
          ps.setString(5, tbl_factura_medicamentos.getValueAt(i, 3).toString());
     
            if(ps.executeUpdate() > 0)
            {
            }
            
//        
                 
        }   
        //Mensaje de error
        catch (SQLException ex) {
        Logger.getLogger(formularios_de_control_y_acceso.frm_control_usuarios.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(null, "error "+ex);
            }
 
    }
        guardar();
        imprimir();
       
    }//GEN-LAST:event_btn_guardareimprimirfacturamedicActionPerformed

    private void btn_agregarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarproductoActionPerformed
        // TODO add your handling code here:
        monto();
        
        //Declaración de variables y asignación de sus respectivos campos
        String cod = txt_codigomedic.getText();
        String nombre = txt_nombremedic.getText();
        String precio = txt_montomedic.getText();
        String cantidad = txt_cantidadmedic.getText();

        detalles.addRow(new Object[]{cod,nombre,precio,cantidad});
        suma();
        
        txt_codigomedic.setText("");
        txt_cantidadmedic.setText("");
        txt_nombremedic.setText("");
        txt_preciomedic.setText("");
        txt_montomedic.setText("");
    }//GEN-LAST:event_btn_agregarproductoActionPerformed

    private void txt_montomedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montomedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_montomedicActionPerformed

    private void btn_removerproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerproductoActionPerformed
        // Remueve un medicamento de la tabla de factura
        DefaultTableModel dtm = (DefaultTableModel) tbl_factura_medicamentos.getModel();
        dtm.removeRow(tbl_factura_medicamentos.getSelectedRow());
        suma();
        
    }//GEN-LAST:event_btn_removerproductoActionPerformed

    private void txt_nofacturamedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nofacturamedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nofacturamedicActionPerformed

    private void btn_buscarclientemedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarclientemedicActionPerformed
        // TODO add your handling code here:
        
        //Abre el formulario de busqueda de cliente
        frm_buscar_cliente_medicamentos cliente_medic= new frm_buscar_cliente_medicamentos();
        cliente_medic.setVisible(true);
    }//GEN-LAST:event_btn_buscarclientemedicActionPerformed

    private void txt_montototalfacturamedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_montototalfacturamedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_montototalfacturamedicActionPerformed

    private void btn_registrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarclienteActionPerformed
        // TODO add your handling code here:
        
        //Abre el formulario de registro de cliente
        frm_registrar_cliente form = new frm_registrar_cliente();
        form.setVisible(true);
    }//GEN-LAST:event_btn_registrarclienteActionPerformed

    private void txt_nombreempleadomedicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreempleadomedicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreempleadomedicActionPerformed

    private void btn_cerrarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarsesionActionPerformed
        // TODO add your handling code here:
        //Cierra sesión y abre el login
        frm_login form = new frm_login();
        form.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrarsesionActionPerformed

    private void txt_cantidadmedicKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cantidadmedicKeyPressed
        // TODO add your handling code here:
        monto();
    }//GEN-LAST:event_txt_cantidadmedicKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_facturacion_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_facturacion_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_facturacion_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_facturacion_medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        //Evento para visualizar facturación de medicamentos
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_facturacion_medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarproducto;
    private javax.swing.JButton btn_buscarclientemedic;
    private javax.swing.JButton btn_cerrarsesion;
    private javax.swing.JButton btn_guardareimprimirfacturamedic;
    private javax.swing.JButton btn_nuevafacturamedic;
    private javax.swing.JButton btn_registrarcliente;
    public javax.swing.JButton btn_removerproducto;
    private javax.swing.JButton btn_vertodoslosproductos;
    private javax.swing.JPanel jp_contenedoratendidopor;
    private javax.swing.JPanel jp_contenedordatos;
    private javax.swing.JPanel jp_contenedordatoscli;
    private javax.swing.JPanel jp_contenedordatosfactura;
    private javax.swing.JPanel jp_contenedordatosgen;
    private javax.swing.JPanel jp_desa;
    private javax.swing.JPanel jp_marcoinferior;
    private javax.swing.JPanel jp_marcosuperior;
    private javax.swing.JScrollPane jsc_tblfactura;
    private javax.swing.JLabel lbl_apellidosclientemedic;
    private javax.swing.JLabel lbl_atendidopormedic;
    private javax.swing.JLabel lbl_cantidadmedic;
    private javax.swing.JLabel lbl_codigomedic;
    private javax.swing.JLabel lbl_datosclientemedic;
    private javax.swing.JLabel lbl_datosgeneralesmedic;
    private javax.swing.JLabel lbl_des;
    private javax.swing.JLabel lbl_facturacionmedicamento;
    private javax.swing.JLabel lbl_fechafacturamedic;
    private javax.swing.JLabel lbl_idclientemedic;
    private javax.swing.JLabel lbl_logomedicamento;
    private javax.swing.JLabel lbl_montomedic;
    private javax.swing.JLabel lbl_montototalfacturamedic;
    private javax.swing.JLabel lbl_nofacturamedicamento;
    private javax.swing.JLabel lbl_nom;
    private javax.swing.JLabel lbl_nombreclientemedic;
    private javax.swing.JLabel lbl_nombremedic;
    private javax.swing.JLabel lbl_nombrempleadomedic;
    private javax.swing.JLabel lbl_preciomedic;
    public static javax.swing.JTable tbl_factura_medicamentos;
    public static javax.swing.JTextField txt_apellidosclientemedic;
    public static javax.swing.JTextField txt_cantidadmedic;
    public static javax.swing.JTextField txt_codigomedic;
    public static javax.swing.JTextField txt_fechafacturamedic;
    public static javax.swing.JTextField txt_idclientemedic;
    public static javax.swing.JTextField txt_montomedic;
    public static javax.swing.JTextField txt_montototalfacturamedic;
    public static javax.swing.JTextField txt_nofacturamedic;
    public static javax.swing.JTextField txt_nombreclientemedic;
    public static javax.swing.JTextField txt_nombreempleadomedic;
    public static javax.swing.JTextField txt_nombremedic;
    public static javax.swing.JTextField txt_preciomedic;
    // End of variables declaration//GEN-END:variables
}
